# Generated by Django 4.1 on 2023-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_text_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='D&Donald', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(default='assistant', max_length=200),
        ),
    ]
