# Generated by Django 4.1 on 2023-03-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messageaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageaudio',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='chat.message'),
        ),
    ]
